CREATE TYPE "public"."transaction_status" AS ENUM('pending', 'completed', 'failed');--> statement-breakpoint
CREATE TABLE "whop-test_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whop-test_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recipientId" integer NOT NULL,
	"senderId" integer NOT NULL,
	"amount" integer NOT NULL,
	"pending" "transaction_status" NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "whop-test_transactions" ADD CONSTRAINT "whop-test_transactions_recipientId_whop-test_profiles_id_fk" FOREIGN KEY ("recipientId") REFERENCES "public"."whop-test_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "whop-test_transactions" ADD CONSTRAINT "whop-test_transactions_senderId_whop-test_profiles_id_fk" FOREIGN KEY ("senderId") REFERENCES "public"."whop-test_profiles"("id") ON DELETE cascade ON UPDATE no action;